// generated by stringer -type Message message.go; DO NOT EDIT

package ipmsg

import "fmt"

const _Message_name = "NOOPERATIONBR_ENTRYBR_EXITANSENTRYBR_ABSENCEBR_ISGETLISTOKGETLISTGETLISTANSLISTBR_ISGETLIST2SENDMSGRECVMSGREADMSGDELMSGANSREADMSGGETINFOSENDINFOGETABSENCEINFOSENDABSENCEINFOGETFILEDATRELEASEFILGETDIRFILEGETPUBKEYANSPUBKEYMODESENDCHECKSECRETBROADCASTMULTICASTNOPOPUPAUTORETRETRYPASSWORDNOLOGNEWMUTINOADDLISTREADCHECKFILEATTACHENCRYPT"

var _Message_map = map[Message]string{
	0:       _Message_name[0:11],
	1:       _Message_name[11:19],
	2:       _Message_name[19:26],
	3:       _Message_name[26:34],
	4:       _Message_name[34:44],
	16:      _Message_name[44:56],
	17:      _Message_name[56:65],
	18:      _Message_name[65:72],
	19:      _Message_name[72:79],
	24:      _Message_name[79:92],
	32:      _Message_name[92:99],
	33:      _Message_name[99:106],
	48:      _Message_name[106:113],
	49:      _Message_name[113:119],
	50:      _Message_name[119:129],
	64:      _Message_name[129:136],
	65:      _Message_name[136:144],
	80:      _Message_name[144:158],
	81:      _Message_name[158:173],
	96:      _Message_name[173:183],
	97:      _Message_name[183:193],
	98:      _Message_name[193:203],
	114:     _Message_name[203:212],
	115:     _Message_name[212:221],
	255:     _Message_name[221:225],
	256:     _Message_name[225:234],
	512:     _Message_name[234:240],
	1024:    _Message_name[240:249],
	2048:    _Message_name[249:258],
	4096:    _Message_name[258:265],
	8192:    _Message_name[265:272],
	16384:   _Message_name[272:277],
	32768:   _Message_name[277:285],
	131072:  _Message_name[285:290],
	262144:  _Message_name[290:297],
	524288:  _Message_name[297:306],
	1048576: _Message_name[306:315],
	2097152: _Message_name[315:325],
	4194304: _Message_name[325:332],
}

func (i Message) String() string {
	if str, ok := _Message_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Message(%d)", i)
}
